# Generated by Django 5.0.4 on 2024-04-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0004_alter_organizer_options_alter_organizer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email_has_been_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
