# Generated by Django 5.0.4 on 2024-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0005_attendee_email_has_been_forwarded_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
