# Generated by Django 5.0.4 on 2024-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baydenApp', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
